### ISSUE TITLE
"Cannot read property 'bind' of null" error in Series.componentWillUnmount

### ISSUE THREAD

**Issue by matsomo** [whawker/react-jsx-highcharts#172]
#### Bug or Feature Request?
Bug?

#### Description
I have a row of tabs with the same variwide chart component being rendered on each page. During navigation between them, the following exception happens:

Series.componentWillUnmount
> 105 | }, {
  106 |   key: 'componentWillUnmount',
  107 |   value: function componentWillUnmount() {
 108 |     attempt(this.series.remove.bind(this.series)); // Series may have already been removed, i.e. when Axis unmounted
  109 |   }
  110 | }, {
  111 |   key: 'render',

Stack:
TypeError: Cannot read property 'bind' of null
    at Series.componentWillUnmount (http://localhost:3000/static/js/1.chunk.js:347258:93)
    at callComponentWillUnmountWithTimer (http://localhost:3000/static/js/1.chunk.js:335834:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:320715:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:320764:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:320814:35)
    at safelyCallComponentWillUnmount (http://localhost:3000/static/js/1.chunk.js:335841:9)
    at commitUnmount (http://localhost:3000/static/js/1.chunk.js:336104:15)
    at commitNestedUnmounts (http://localhost:3000/static/js/1.chunk.js:336140:9)
    at unmountHostComponents (http://localhost:3000/static/js/1.chunk.js:336423:11)
    at commitDeletion (http://localhost:3000/static/js/1.chunk.js:336480:9)
    at commitAllHostEffects (http://localhost:3000/static/js/1.chunk.js:337219:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:320715:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:320764:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:320814:35)
    at commitRoot (http://localhost:3000/static/js/1.chunk.js:337412:11)
    at completeRoot (http://localhost:3000/static/js/1.chunk.js:338906:7)
    at performWorkOnRoot (http://localhost:3000/static/js/1.chunk.js:338828:13)
    at performWork (http://localhost:3000/static/js/1.chunk.js:338730:11)
    at performSyncWork (http://localhost:3000/static/js/1.chunk.js:338703:7)
    at requestWork (http://localhost:3000/static/js/1.chunk.js:338580:9)
    at scheduleWork (http://localhost:3000/static/js/1.chunk.js:338373:9)
    at Object.enqueueSetState (http://localhost:3000/static/js/1.chunk.js:332647:9)
    at Connect.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/1.chunk.js:356260:20)
    at Connect.onStateChange (http://localhost:3000/static/js/1.chunk.js:353558:16)
    at Object.notify (http://localhost:3000/static/js/1.chunk.js:354229:21)
    at Subscription.notifyNestedSubs (http://localhost:3000/static/js/1.chunk.js:354266:20)
    at Connect.onStateChange (http://localhost:3000/static/js/1.chunk.js:353555:16)
    at Object.dispatch (http://localhost:3000/static/js/1.chunk.js:358174:7)
    at dispatch (<anonymous>:1:38223)
    at http://localhost:3000/static/js/main.chunk.js:3384:18
    at http://localhost:3000/static/js/main.chunk.js:15733:30
    at http://localhost:3000/static/js/1.chunk.js:357933:16
    at dispatch (http://localhost:3000/static/js/1.chunk.js:358573:28)
    at _callee$ (http://localhost:3000/static/js/main.chunk.js:11400:24)
    at tryCatch (http://localhost:3000/static/js/1.chunk.js:358774:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/1.chunk.js:358993:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/1.chunk.js:358827:21)
    at asyncGeneratorStep (http://localhost:3000/static/js/1.chunk.js:233206:24)
    at _next (http://localhost:3000/static/js/1.chunk.js:233228:9)

The exception only happens if a series component is supplied to an axis component.

#### How to reproduce
Create an array of arrays with 3 values ["point name", y, z] and pass it into a VariwideSeries component's "data" property. Supply the VariwideSeries to an Axis component.

#### Live demo demonstrating bug
I could not reproduce the error, but I've made a simplified version with the same test data.
https://stackblitz.com/edit/react-5fdeqd

#### Versions
* React JSX Highcharts version: 3.2.0
* Highcharts version: 6.1.4
* React version: 16.5.2

I've also tried with the same versions as in the demo;
* React JSX Highcharts version: 3.3.0
* Highcharts version: 6.2.0
* React version: 16.5.0

**Comment by anajavi** [comment]
Do you have different stacktrace using version 3.3.0?

That exception cannot happen on 3.3.0 because of this commit: https://github.com/whawker/react-jsx-highcharts/commit/968a0b954fcb7245acdf72cf493c1fb0a4cc7dcd

**Comment by matsomo** [comment]
Hi, I get the same stacktrace with version 3.3.0

**Comment by matsomo** [comment]
Hi again, never mind. Got it working with version 3.3.0. I forgot to restart the node server to see the effect.

Current package.json
react-jsx-highcharts: 3.3.0
highcharts: 6.2.0
react: 16.5.2
