### ISSUE TITLE
Version v5 alpha feedback and issues

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#361]
This issue exists to feedback any issues discovered with version 5.

Version 5 can be tested by installing it with:
```
npm install react-jsx-highcharts@^5.0.0-alpha.0
```

**Breaking changes:**
- Drop support for react < 17
- Drop support for highcharts < 9.1.2
- Drop support for old browsers. The supported browsers are:
  - chrome >= 81
  - edge >= 81
  - firefox >= 78
  - ios >= 12
  - safari >= 12

**New Features:**
- Support react 18 #360
- Axis events can be updated #333

**Other changes:**
- prop-types are removed #354 
- chart is destroyed on unmount without requestAnimationFrame #332

**Comment by veloek** [comment]
Testing this version now and it looks good so far 🙂

**Comment by anajavi** [comment]
> Testing this version now and it looks good so far 🙂

Nice! Did you test with react v18?

**Comment by veloek** [comment]
Yes, using React 18. Had to hold off on Highcharts 10 though due to some issues with offline exporting that we haven't solved yet.

**Comment by anajavi** [comment]
@whawker I guess the v5 could be released, what do you think?

**Comment by anajavi** [comment]
@whawker do you mind if I release the v5?

**Comment by anajavi** [comment]
I tried to upgrade to highcharts v10.1.0, and tests started to fail, so maybe the v5 shouldn't be released yet :(

**Comment by anajavi** [comment]
I can't reproduce the test failures in normal react app. Those tests probably fail because jsdom doesn't set width and height for elements.

The error:
```
    TypeError: Cannot read properties of undefined (reading 'length')

      47 |       // they can be accessed
      48 |       if (axis.plotLinesAndBands && axis.plotLinesAndBands.length > 0) {
    > 49 |         axis.update(updateProps, true);
         |              ^
      50 |       } else {
      51 |         axis.update(updateProps, false);
      52 |         chart.needsRedraw();

      at a.length [as setTickPositions] (../../node_modules/highcharts/highcharts.src.js:20183:25)
      at a.setTickPositions [as setTickInterval] (../../node_modules/highcharts/highcharts.src.js:20087:17)
      at a.setTickInterval [as setScale] (../../node_modules/highcharts/highcharts.src.js:20560:21)
      at setScale (../../node_modules/highcharts/highcharts.src.js:30727:21)
          at Array.forEach (<anonymous>)
      at a.forEach [as redraw] (../../node_modules/highcharts/highcharts.src.js:30725:17)
      at a.redraw (../../node_modules/highcharts/highcharts.src.js:21978:21)
      at update (src/components/Axis/Axis.js:49:14)
      at commitHookEffectListMount (../../node_modules/react-dom/cjs/react-dom.development.js:23049:26)
      at commitPassiveMountOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24821:11)
      at commitPassiveMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24781:9)
      at commitPassiveMountEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24768:7)
      at commitPassiveMountEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24756:3)
      at flushPassiveEffectsImpl (../../node_modules/react-dom/cjs/react-dom.development.js:26990:3)
      at flushPassiveEffects (../../node_modules/react-dom/cjs/react-dom.development.js:26935:14)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:26725:9
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2665:24)
      at act (../../node_modules/react/cjs/react.development.js:2580:11)
      at ../../node_modules/@testing-library/react/dist/act-compat.js:57:25
      at renderRoot (../../node_modules/@testing-library/react/dist/pure.js:159:26)
      at Object.rerender (../../node_modules/@testing-library/react/dist/pure.js:178:7)
      at Object.rerender (test/components/PlotBandLine/PlotBandLineLabel.integration.spec.js:74:15)
```

**Comment by anajavi** [comment]
Test failure in highcharts@10.1.0 is a bug in highcharts itself:
https://github.com/highcharts/highcharts/issues/17300

**Comment by whawker** [comment]
Happy to push v5 out!

**Comment by anajavi** [comment]
v5 is now released

**Comment by anajavi** [comment]
@whawker can you please upgrade the reproduction template in https://stackblitz.com/edit/base-chart-example to new version. Here is my fork of it with React 18 createRoot https://stackblitz.com/edit/base-chart-example-rnw6ff?file=index.js

**Comment by whawker** [comment]
@anajavi updated the examples repo :+1:
